<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$helper = $this->helper("Webkul\Marketplace\Helper\Data");
?>
<input type="hidden" name="seller_panel" id="seller_panel" data-form-part="customer_form" value="<?php echo $helper->getParam("seller_panel"); ?>" />