<div id="owl-demo" data-mage-init='{
  "OwlCarousel":{
        "autoPlay": 3000,
        "items" : 4,
        "itemsDesktop" : [1199,3],
        "itemsDesktopSmall" : [979,3]
  }
}
'>
    <div class="item"><img src="https://i.ytimg.com/vi/8VgiIMfCS7c/maxresdefault.jpg" alt="Owl Image"></div>
    <div class="item"><img src="https://i.ytimg.com/vi/gomxvzSgpAI/maxresdefault.jpg" alt="Owl Image"></div>
    <div class="item"><img src="https://i.redd.it/wr9ox205yro01.jpg" alt="Owl Image"></div>
    <div class="item"><img src="https://image.winudf.com/v2/image1/Y29tLmlicy5raW5nLm9mLmZsZWV0LnNlYS5iYXR0bGUuc2ltdWxhdG9yLmdhbWVfc2NyZWVuXzRfMTU3Mjc5NTQyMl8wODI/screen-4.jpg?fakeurl=1&type=.jpg" alt="Owl Image"></div>
    <div class="item"><img src="https://i.ytimg.com/vi/7PQsFqfREfA/maxresdefault.jpg" alt="Owl Image"></div>
    <div class="item"><img src="https://image.winudf.com/v2/image1/Y29tLmlicy5raW5nLm9mLmZsZWV0LnNlYS5iYXR0bGUuc2ltdWxhdG9yLmdhbWVfc2NyZWVuXzNfMTU3Mjc5NTQyMl8wOTQ/screen-3.jpg?fakeurl=1&type=.jpg" alt="Owl Image"></div>
    <div class="item"><img src="https://i.ytimg.com/vi/-2pUbtI6Phw/maxresdefault.jpg" alt="Owl Image"></div>
    <div class="item"><img src="https://image.winudf.com/v2/image1/Y29tLmlicy5raW5nLm9mLmZsZWV0LnNlYS5iYXR0bGUuc2ltdWxhdG9yLmdhbWVfc2NyZWVuXzBfMTU3Mjc5NTQyMF8wNTQ/screen-0.jpg?fakeurl=1&type=.jpg" alt="Owl Image"></div>
</div>